---
title: "Fit the Continuous-Time Vector Autoregressive Model Using the dynr Package"
author: Ivan Jacob Agaloos Pesigan
date: "2025-01-06"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @RCoreTeam-2024
  @Ou-Hunter-Chow-2019
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fit the Continuous-Time Vector Autoregressive Model Using the dynr Package}
  %\VignetteEngine{quarto::quarto}
  %\VignetteEncoding{UTF-8}
---





## Data Generation Using the `SimSSMOUFixed` Function from the `simStateSpace` Package


``` r
n
#> [1] 50
time
#> [1] 100
delta_t
#> [1] 0.1
mu0
#> [1] 0 0 0
sigma0
#>      [,1] [,2] [,3]
#> [1,]  1.0  0.2  0.2
#> [2,]  0.2  1.0  0.2
#> [3,]  0.2  0.2  1.0
sigma0_l
#>      [,1]      [,2]      [,3]
#> [1,]  1.0 0.0000000 0.0000000
#> [2,]  0.2 0.9797959 0.0000000
#> [3,]  0.2 0.1632993 0.9660918
mu
#> [1] 0 0 0
phi
#>        [,1]   [,2]   [,3]
#> [1,] -0.357  0.000  0.000
#> [2,]  0.771 -0.511  0.000
#> [3,] -0.450  0.729 -0.693
sigma
#>             [,1]       [,2]        [,3]
#> [1,]  0.24455556 0.02201587 -0.05004762
#> [2,]  0.02201587 0.07067800  0.01539456
#> [3,] -0.05004762 0.01539456  0.07553061
sigma_l
#>             [,1]      [,2]     [,3]
#> [1,]  0.49452559 0.0000000 0.000000
#> [2,]  0.04451917 0.2620993 0.000000
#> [3,] -0.10120330 0.0759256 0.243975
nu
#> [1] 0 0 0
lambda
#>      [,1] [,2] [,3]
#> [1,]    1    0    0
#> [2,]    0    1    0
#> [3,]    0    0    1
theta
#>      [,1] [,2] [,3]
#> [1,]  0.2  0.0  0.0
#> [2,]  0.0  0.2  0.0
#> [3,]  0.0  0.0  0.2
theta_l
#>           [,1]      [,2]      [,3]
#> [1,] 0.4472136 0.0000000 0.0000000
#> [2,] 0.0000000 0.4472136 0.0000000
#> [3,] 0.0000000 0.0000000 0.4472136
```


``` r
library(simStateSpace)
sim <- SimSSMOUFixed(
  n = n,
  time = time,
  delta_t = delta_t,
  mu0 = mu0,
  sigma0_l = sigma0_l,
  mu = mu,
  phi = phi,
  sigma_l = sigma_l,
  nu = nu,
  lambda = lambda,
  theta_l = theta_l,
  type = 0
)
data <- as.data.frame(sim)
colnames(data) <- c("id", "time", "x", "m", "y")
head(data)
#>   id time          x          m        y
#> 1  1  0.0 -0.3504435 0.41877429 2.611996
#> 2  1  0.1 -0.5920330 1.07433208 1.669272
#> 3  1  0.2 -0.7619855 1.21483834 2.369837
#> 4  1  0.3 -1.6964652 0.21209722 2.128531
#> 5  1  0.4 -1.2282686 0.09950326 1.891140
#> 6  1  0.5  0.1433985 0.66784226 2.036033
```

## Model Fitting

We use the `dynr` package to fit the continuous-time vector autoregressive model.




``` r
library(dynr)
```

### Prepare the Data


``` r
dynr_data <- dynr.data(
  dataframe = data,
  id = "id",
  time = "time",
  observed = c("x", "m", "y")
)
```

### Prepare the Initial Condition


``` r
dynr_initial <- prep.initial(
  values.inistate = c(
    0, 0, 0
  ),
  params.inistate = c(
    "mu0_1", "mu0_2", "mu0_3"
  ),
  values.inicov = matrix(
    data = c(
      1.0, 0.2, 0.2,
      0.2, 1.0, 0.2,
      0.2, 0.2, 1.0
    ),
    nrow = 3
  ),
  params.inicov = matrix(
    data = c(
      "sigma0_11", "sigma0_12", "sigma0_13",
      "sigma0_12", "sigma0_22", "sigma0_23",
      "sigma0_13", "sigma0_23", "sigma0_33"
    ),
    nrow = 3
  )
)
```

### Prepare the Measurement Model


``` r
dynr_measurement <- prep.measurement(
  values.load = diag(3),
  params.load = matrix(
    data = "fixed",
    nrow = 3,
    ncol = 3
  ),
  state.names = c("eta_x", "eta_m", "eta_y"),
  obs.names = c("x", "m", "y")
)
```

### Prepare the Dynamic Model


``` r
dynr_dynamics <- prep.formulaDynamics(
  formula = list(
    eta_x ~ phi_11 * eta_x + phi_12 * eta_m + phi_13 * eta_y,
    eta_m ~ phi_21 * eta_x + phi_22 * eta_m + phi_23 * eta_y,
    eta_y ~ phi_31 * eta_x + phi_32 * eta_m + phi_33 * eta_y
  ),
  startval = c(
    phi_11 = -0.2, phi_21 = 0.0, phi_31 = 0.0,
    phi_12 = 0.0, phi_22 = -0.2, phi_32 = 0.0,
    phi_13 = 0.0, phi_23 = 0.0, phi_33 = -0.2
  ),
  isContinuousTime = TRUE
)
```

### Prepare the Noise Matrices


``` r
dynr_noise <- prep.noise(
  values.latent = matrix(
    data = 0.2 * diag(3),
    nrow = 3
  ),
  params.latent = matrix(
    data = c(
      "sigma_11", "sigma_12", "sigma_13",
      "sigma_12", "sigma_22", "sigma_23",
      "sigma_13", "sigma_23", "sigma_33"
    ),
    nrow = 3
  ),
  values.observed = 0.2 * diag(3),
  params.observed = matrix(
    data = c(
      "theta_11", "fixed", "fixed",
      "fixed", "theta_22", "fixed",
      "fixed", "fixed", "theta_33"
    ),
    nrow = 3
  )
)
```

### Prepare the Model

In this example, we increase the maximum evaluations in the optimization process
and add lower and upper bounds on some parameters.


``` r
dynr_model <- dynr.model(
  data = dynr_data,
  initial = dynr_initial,
  measurement = dynr_measurement,
  dynamics = dynr_dynamics,
  noise = dynr_noise,
  outfile = tempfile(
    paste0(
      "src-",
      format(
        Sys.time(),
        "%Y-%m-%d-%H-%M-%OS3"
      )
    ),
    fileext = ".c"
  )
)
dynr_model@options$maxeval <- 100000
lb <- ub <- rep(NA, times = length(dynr_model$xstart))
names(ub) <- names(lb) <- names(dynr_model$xstart)
lb[
  c(
    "sigma0_11",
    "sigma0_22",
    "sigma0_33"
  )
] <- .Machine$double.xmin
lb[
  c(
    "phi_11", "phi_21", "phi_31",
    "phi_12", "phi_22", "phi_32",
    "phi_13", "phi_23", "phi_33"
  )
] <- -1.5
ub[
  c(
    "phi_11", "phi_21", "phi_31",
    "phi_12", "phi_22", "phi_32",
    "phi_13", "phi_23", "phi_33"
  )
] <- 1.5
lb[
  c(
    "sigma_11",
    "sigma_22",
    "sigma_33"
  )
] <- .Machine$double.xmin
lb[
  c(
    "theta_11",
    "theta_22",
    "theta_33"
  )
] <- .Machine$double.xmin
dynr_model$lb <- lb
dynr_model$ub <- ub
```

### Fit the Model


``` r
fit <- dynr.cook(
  dynr_model,
  verbose = FALSE
)
#> [1] "Get ready!!!!"
#> using C compiler: ‘gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0’
#> Optimization function called.
#> Starting Hessian calculation ...
#> Finished Hessian calculation.
#> Original exit flag:  3 
#> Modified exit flag:  3 
#> Optimization terminated successfully: ftol_rel or ftol_abs was reached. 
#> Original fitted parameters:  -0.2938068 0.8243958 -0.4543161 -0.07191553 
#> -0.5689988 0.707647 0.0257906 0.08266777 -0.6875018 -1.444748 0.07916771 
#> -0.2743246 -2.582169 0.1772108 -2.804538 -1.604288 -1.652135 -1.622277 
#> -0.06854664 0.0845735 0.1157207 -0.05902916 0.1716259 0.1095353 0.3797741 
#> -0.08084045 -0.07765938 
#> 
#> Transformed fitted parameters:  -0.2938068 0.8243958 -0.4543161 -0.07191553 
#> -0.5689988 0.707647 0.0257906 0.08266777 -0.6875018 0.2358055 0.01866819 
#> -0.06468727 0.07708775 0.008277735 0.08065449 0.2010327 0.1916402 0.1974485 
#> -0.06854664 0.0845735 0.1157207 0.9426793 0.1617882 0.1032566 1.489721 
#> -0.1004635 0.9461439 
#> 
#> Doing end processing
#> Successful trial
#> Total Time: 6.070862 
#> Backend Time: 6.043654
summary(fit)
#> Coefficients:
#>            Estimate Std. Error t value  ci.lower  ci.upper Pr(>|t|)    
#> phi_11    -0.293807   0.082037  -3.581 -0.454596 -0.133018   0.0002 ***
#> phi_21     0.824396   0.056810  14.511  0.713049  0.935742   <2e-16 ***
#> phi_31    -0.454316   0.057798  -7.860 -0.567598 -0.341034   <2e-16 ***
#> phi_12    -0.071916   0.068497  -1.050 -0.206167  0.062336   0.1469    
#> phi_22    -0.568999   0.048437 -11.747 -0.663933 -0.474065   <2e-16 ***
#> phi_32     0.707647   0.048777  14.508  0.612046  0.803248   <2e-16 ***
#> phi_13     0.025791   0.062504   0.413 -0.096715  0.148296   0.3400    
#> phi_23     0.082668   0.043422   1.904 -0.002439  0.167774   0.0285 *  
#> phi_33    -0.687502   0.044179 -15.562 -0.774092 -0.600912   <2e-16 ***
#> sigma_11   0.235806   0.022675  10.399  0.191364  0.280247   <2e-16 ***
#> sigma_12   0.018668   0.010037   1.860 -0.001003  0.038340   0.0315 *  
#> sigma_13  -0.064687   0.010761  -6.012 -0.085778 -0.043597   <2e-16 ***
#> sigma_22   0.077088   0.009440   8.166  0.058586  0.095590   <2e-16 ***
#> sigma_23   0.008278   0.006642   1.246 -0.004740  0.021296   0.1064    
#> sigma_33   0.080654   0.010183   7.921  0.060697  0.100612   <2e-16 ***
#> theta_11   0.201033   0.005104  39.384  0.191028  0.211037   <2e-16 ***
#> theta_22   0.191640   0.004372  43.833  0.183071  0.200209   <2e-16 ***
#> theta_33   0.197449   0.004520  43.680  0.188589  0.206308   <2e-16 ***
#> mu0_1     -0.068547   0.141770  -0.484 -0.346411  0.209318   0.3144    
#> mu0_2      0.084573   0.176698   0.479 -0.261749  0.430896   0.3161    
#> mu0_3      0.115721   0.141262   0.819 -0.161147  0.392589   0.2064    
#> sigma0_11  0.942679   0.202183   4.662  0.546407  1.338951   <2e-16 ***
#> sigma0_12  0.161788   0.178313   0.907 -0.187698  0.511275   0.1821    
#> sigma0_13  0.103257   0.142840   0.723 -0.176704  0.383217   0.2349    
#> sigma0_22  1.489721   0.309031   4.821  0.884031  2.095412   <2e-16 ***
#> sigma0_23 -0.100464   0.177101  -0.567 -0.447575  0.246648   0.2853    
#> sigma0_33  0.946144   0.202058   4.683  0.550117  1.342171   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> -2 log-likelihood value at convergence = 21626.57
#> AIC = 21680.57
#> BIC = 21856.53
coefs <- coef(fit)
vcovs <- vcov(fit)
```

### Extract Matrices from the Fitted Model to use in cTMed


``` r
phi_names <- c(
  "phi_11", "phi_21", "phi_31",
  "phi_12", "phi_22", "phi_32",
  "phi_13", "phi_23", "phi_33"
)
sigma_names <- c(
  "sigma_11", "sigma_12", "sigma_13",
  "sigma_12", "sigma_22", "sigma_23",
  "sigma_13", "sigma_23", "sigma_33"
)
sigma_vech_names <- c(
  "sigma_11", "sigma_12", "sigma_13",
  "sigma_22", "sigma_23",
  "sigma_33"
)
theta_names <- c(
  "phi_11", "phi_21", "phi_31",
  "phi_12", "phi_22", "phi_32",
  "phi_13", "phi_23", "phi_33",
  "sigma_11", "sigma_12", "sigma_13",
  "sigma_22", "sigma_23",
  "sigma_33"
)
phi <- matrix(
  data = coefs[phi_names],
  nrow = 3,
  ncol = 3
)
sigma <- matrix(
  data = coefs[sigma_names],
  nrow = 3,
  ncol = 3
)
theta <- coefs[theta_names]
vcov_phi_vec <- vcovs[phi_names, phi_names]
vcov_sigma_vech <- vcovs[sigma_vech_names, sigma_vech_names]
vcov_theta <- vcovs[theta_names, theta_names]
```

#### Estimated Drift Matrix with Corresponding Sampling Covariance Matrix


``` r
phi
#>            [,1]        [,2]        [,3]
#> [1,] -0.2938068 -0.07191553  0.02579060
#> [2,]  0.8243958 -0.56899879  0.08266777
#> [3,] -0.4543161  0.70764697 -0.68750180
vcov_phi_vec
#>               phi_11        phi_21        phi_31        phi_12        phi_22
#> phi_11  0.0067300381  3.324449e-04 -0.0014433702 -0.0048489832 -2.780506e-04
#> phi_21  0.0003324449  3.227422e-03 -0.0001201137 -0.0001296433 -2.414974e-03
#> phi_31 -0.0014433702 -1.201137e-04  0.0033406045  0.0009881196  1.104566e-04
#> phi_12 -0.0048489832 -1.296433e-04  0.0009881196  0.0046918472  1.917147e-04
#> phi_22 -0.0002780506 -2.414974e-03  0.0001104566  0.0001917147  2.346104e-03
#> phi_32  0.0010427977  3.956062e-05 -0.0024634576 -0.0010068866 -8.381904e-05
#> phi_13  0.0033259374  4.746460e-05 -0.0006218729 -0.0034075126 -8.504281e-05
#> phi_23  0.0002260214  1.682145e-03 -0.0001034612 -0.0001920922 -1.722776e-03
#> phi_33 -0.0007413127 -7.561513e-06  0.0016991684  0.0007604268  3.145837e-05
#>               phi_32        phi_13        phi_23        phi_33
#> phi_11  1.042798e-03  3.325937e-03  2.260214e-04 -7.413127e-04
#> phi_21  3.956062e-05  4.746460e-05  1.682145e-03 -7.561513e-06
#> phi_31 -2.463458e-03 -6.218729e-04 -1.034612e-04  1.699168e-03
#> phi_12 -1.006887e-03 -3.407513e-03 -1.920922e-04  7.604268e-04
#> phi_22 -8.381904e-05 -8.504281e-05 -1.722776e-03  3.145837e-05
#> phi_32  2.379210e-03  6.796733e-04  1.047972e-04 -1.744253e-03
#> phi_13  6.796733e-04  3.906765e-03  1.796534e-04 -8.796123e-04
#> phi_23  1.047972e-04  1.796534e-04  1.885512e-03 -9.810442e-05
#> phi_33 -1.744253e-03 -8.796123e-04 -9.810442e-05  1.951817e-03
```

#### Process Noise Covariance Matrix with Corresponding Sampling Covariance Matrix


``` r
sigma
#>             [,1]        [,2]         [,3]
#> [1,]  0.23580555 0.018668185 -0.064687274
#> [2,]  0.01866819 0.077087753  0.008277735
#> [3,] -0.06468727 0.008277735  0.080654490
vcov_sigma_vech
#>               sigma_11      sigma_12      sigma_13      sigma_22      sigma_23
#> sigma_11  5.141494e-04  1.289000e-05 -9.389706e-05  1.323280e-06 -5.564875e-06
#> sigma_12  1.289000e-05  1.007335e-04 -3.178174e-06  4.462383e-06 -2.211662e-05
#> sigma_13 -9.389706e-05 -3.178174e-06  1.157892e-04 -4.141411e-07  3.228637e-06
#> sigma_22  1.323280e-06  4.462383e-06 -4.141411e-07  8.911344e-05 -2.704800e-06
#> sigma_23 -5.564875e-06 -2.211662e-05  3.228637e-06 -2.704800e-06  4.411407e-05
#> sigma_33  1.930564e-05  1.458035e-06 -4.738128e-05 -1.425795e-07 -2.561237e-06
#>               sigma_33
#> sigma_11  1.930564e-05
#> sigma_12  1.458035e-06
#> sigma_13 -4.738128e-05
#> sigma_22 -1.425795e-07
#> sigma_23 -2.561237e-06
#> sigma_33  1.036881e-04
```

#### Estimated Drift Matrix and Process Noise Covariance Matrix with Corresponding Sampling Covariance Matrix


``` r
theta
#>       phi_11       phi_21       phi_31       phi_12       phi_22       phi_32 
#> -0.293806758  0.824395787 -0.454316068 -0.071915534 -0.568998793  0.707646967 
#>       phi_13       phi_23       phi_33     sigma_11     sigma_12     sigma_13 
#>  0.025790604  0.082667773 -0.687501799  0.235805548  0.018668185 -0.064687274 
#>     sigma_22     sigma_23     sigma_33 
#>  0.077087753  0.008277735  0.080654490
vcov_theta
#>                 phi_11        phi_21        phi_31        phi_12        phi_22
#> phi_11    6.730038e-03  3.324449e-04 -1.443370e-03 -4.848983e-03 -2.780506e-04
#> phi_21    3.324449e-04  3.227422e-03 -1.201137e-04 -1.296433e-04 -2.414974e-03
#> phi_31   -1.443370e-03 -1.201137e-04  3.340605e-03  9.881196e-04  1.104566e-04
#> phi_12   -4.848983e-03 -1.296433e-04  9.881196e-04  4.691847e-03  1.917147e-04
#> phi_22   -2.780506e-04 -2.414974e-03  1.104566e-04  1.917147e-04  2.346104e-03
#> phi_32    1.042798e-03  3.956062e-05 -2.463458e-03 -1.006887e-03 -8.381904e-05
#> phi_13    3.325937e-03  4.746460e-05 -6.218729e-04 -3.407513e-03 -8.504281e-05
#> phi_23    2.260214e-04  1.682145e-03 -1.034612e-04 -1.920922e-04 -1.722776e-03
#> phi_33   -7.413127e-04 -7.561513e-06  1.699168e-03  7.604268e-04  3.145837e-05
#> sigma_11 -1.088979e-03 -1.389511e-04  2.494061e-04  6.145374e-04  8.054203e-05
#> sigma_12  1.006043e-04 -2.410466e-04 -3.911655e-05 -1.267265e-04  1.279789e-04
#> sigma_13  1.339640e-04  2.989171e-05 -2.755394e-04 -3.605321e-05 -1.107738e-05
#> sigma_22 -5.160449e-06  1.147607e-04  1.164277e-05  6.530523e-06 -1.400587e-04
#> sigma_23 -3.974778e-06  2.829115e-05  5.379623e-05  1.089586e-05  7.992137e-06
#> sigma_33 -2.786162e-05 -1.366194e-05  5.740578e-05  7.123166e-06  5.304245e-06
#>                 phi_32        phi_13        phi_23        phi_33      sigma_11
#> phi_11    1.042798e-03  3.325937e-03  2.260214e-04 -7.413127e-04 -1.088979e-03
#> phi_21    3.956062e-05  4.746460e-05  1.682145e-03 -7.561513e-06 -1.389511e-04
#> phi_31   -2.463458e-03 -6.218729e-04 -1.034612e-04  1.699168e-03  2.494061e-04
#> phi_12   -1.006887e-03 -3.407513e-03 -1.920922e-04  7.604268e-04  6.145374e-04
#> phi_22   -8.381904e-05 -8.504281e-05 -1.722776e-03  3.145837e-05  8.054203e-05
#> phi_32    2.379210e-03  6.796733e-04  1.047972e-04 -1.744253e-03 -1.424853e-04
#> phi_13    6.796733e-04  3.906765e-03  1.796534e-04 -8.796123e-04 -2.908668e-04
#> phi_23    1.047972e-04  1.796534e-04  1.885512e-03 -9.810442e-05 -4.108758e-05
#> phi_33   -1.744253e-03 -8.796123e-04 -9.810442e-05  1.951817e-03  7.068606e-05
#> sigma_11 -1.424853e-04 -2.908668e-04 -4.108758e-05  7.068606e-05  5.141494e-04
#> sigma_12  4.012613e-05  7.573384e-05 -5.777298e-05 -2.335522e-05  1.289000e-05
#> sigma_13  1.441142e-04 -6.746023e-05 -6.574401e-06 -4.290775e-05 -9.389706e-05
#> sigma_22 -1.295529e-05 -4.072523e-06  8.524950e-05  8.203886e-06  1.323280e-06
#> sigma_23 -6.459865e-05 -3.849502e-06 -4.488710e-05  3.570540e-05 -5.564875e-06
#> sigma_33  1.598727e-05  2.022136e-05  5.808640e-06 -1.016818e-04  1.930564e-05
#>               sigma_12      sigma_13      sigma_22      sigma_23      sigma_33
#> phi_11    1.006043e-04  1.339640e-04 -5.160449e-06 -3.974778e-06 -2.786162e-05
#> phi_21   -2.410466e-04  2.989171e-05  1.147607e-04  2.829115e-05 -1.366194e-05
#> phi_31   -3.911655e-05 -2.755394e-04  1.164277e-05  5.379623e-05  5.740578e-05
#> phi_12   -1.267265e-04 -3.605321e-05  6.530523e-06  1.089586e-05  7.123166e-06
#> phi_22    1.279789e-04 -1.107738e-05 -1.400587e-04  7.992137e-06  5.304245e-06
#> phi_32    4.012613e-05  1.441142e-04 -1.295529e-05 -6.459865e-05  1.598727e-05
#> phi_13    7.573384e-05 -6.746023e-05 -4.072523e-06 -3.849502e-06  2.022136e-05
#> phi_23   -5.777298e-05 -6.574401e-06  8.524950e-05 -4.488710e-05  5.808640e-06
#> phi_33   -2.335522e-05 -4.290775e-05  8.203886e-06  3.570540e-05 -1.016818e-04
#> sigma_11  1.289000e-05 -9.389706e-05  1.323280e-06 -5.564875e-06  1.930564e-05
#> sigma_12  1.007335e-04 -3.178174e-06  4.462383e-06 -2.211662e-05  1.458035e-06
#> sigma_13 -3.178174e-06  1.157892e-04 -4.141411e-07  3.228637e-06 -4.738128e-05
#> sigma_22  4.462383e-06 -4.141411e-07  8.911344e-05 -2.704800e-06 -1.425795e-07
#> sigma_23 -2.211662e-05  3.228637e-06 -2.704800e-06  4.411407e-05 -2.561237e-06
#> sigma_33  1.458035e-06 -4.738128e-05 -1.425795e-07 -2.561237e-06  1.036881e-04
```

## References


