name: Compile LaTeX

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ijapesigan/manctmed:2025-04-07-05390291
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: latex-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    permissions:
      contents: write

    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
        
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      -
        name: Make Project
        run: make build
      -
        name: Make LaTeX
        run: |
          make bibrproject
          make pdf
      - 
        name: Push to the latex branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: latex
          FOLDER: .setup/latex/pdf
          GITHUB_TOKEN: ${{ secrets.PAT }}
      -
        name: Make clean
        run: |
          make bibrproject
          make pdf
