name: Make Project

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ijapesigan/manctmed
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    permissions:
      contents: write
      packages: read
      statuses: write

    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
        
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      -
        name: Clean
        run: |
          make clean
      -
        name: Make Project
        run: |
          make install
          make push
      - 
        name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.PAT }}
          commit_message: "Automated build."
