name: Package Website (GitHub Pages)

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ijapesigan/docs
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-gh-pages-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    permissions:
      contents: write

    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
        
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Checkout 
        uses: actions/checkout@v4
      -
        name: Build Project
        run: make build
      -
        name: Build pkgdown Site
        run: make pkgdown
      -
        name: Add .nojekyll
        run: touch pkgdown/.nojekyll
      -
        name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true
          branch: pkgdown
          folder: pkgdown
